### ISSUE TITLE
Pressing YES on the load round pop-up does nothing

### ISSUE THREAD

**Issue by wizpizz** [doombubbles/time-machine#5]
I am not sure if this is related to [this issue ](https://github.com/doombubbles/time-machine/issues/2) that still persists, but after a loss, when clicked on the round to load, pressing the "yes" button does not do anything and the round is not loaded.

**Comment by MixMough** [comment]
I too am having the same issue

**Comment by doombubbles** [comment]
Try the new version https://github.com/doombubbles/time-machine/releases/tag/1.0.5

**Comment by oenderg** [comment]
> Try the new version [`1.0.5` (release)](https://github.com/doombubbles/time-machine/releases/tag/1.0.5)

Everything seems to work fine, thanks for the quick fix!
