### ISSUE TITLE
Boss event saves fail to load

### ISSUE THREAD

**Issue by Mr-8k** [doombubbles/time-machine#6]
Attempting to load a boss save causes the game to close, not crash. It's as if I'd pressed the quit button, there's nothing notable in the log. The last line is  "Preferences Saved!" with nothing coming before it except the mods loaded at startup. Standard saves appear to work fine.

```
[13:58:12.138] [BloonsTD6_Mod_Helper] Registering ModContent for Useful Utilities...
[13:58:21.321] Preferences Saved!
```

**Comment by doombubbles** [comment]
This should now be fixed with the latest version https://github.com/doombubbles/time-machine/releases/tag/1.0.6
